import test from 'node:test';
import assert from 'node:assert/strict';
import {compileCSharp,parseCSharp,lexCSharp} from '../packages/csharp-compiler/index.js';
import * as DN from '../packages/dotnet-runtime/index.js';
function run(source){const types={};const JB={...DN,Object:DN.DotObject,String:DN.StringApi,Math:DN.MathApi,defineType:(n,t)=>types[n]=t};const r=compileCSharp(source);assert.equal(r.success,true,JSON.stringify(r.diagnostics,null,2));new Function('JB',r.code)(JB);return types;}
test('lexer treats comments and strings as tokens, not replacement candidates',()=>{const r=lexCSharp('class A { string X = @"public class ""Hi"""; /* hi */ }');assert.equal(r.diagnostics.length,0);assert.equal(r.tokens.find(t=>t.kind==='string').value,'public class "Hi"');});
test('classes constructors fields and arithmetic preserve integer division',()=>{const t=run('namespace Demo; public class Counter { private int value; public Counter(int initial) { value = initial; } public int Next() { value += 1; return value / 2; } }');const c=new t['Demo.Counter'](4);assert.equal(c.Next(),2);assert.equal(c.Next(),3);});
test('auto properties initialize and emit notifications',()=>{const t=run('class Model { public string Name { get; set; } = "Ada"; public int Count { get; set; } }');const m=new t.Model();const changes=[];m.PropertyChanged.add((s,e)=>changes.push(e.PropertyName));m.Name='Grace';assert.equal(m.Name,'Grace');assert.deepEqual(changes,['Name']);assert.equal(m.Count,0);});
test('explicit property accessor and nameof',()=>{const t=run('class A { int x; public int Value { get => x; set { x = value; OnPropertyChanged(nameof(Value)); } } }');const a=new t.A();let name;a.PropertyChanged.add((s,e)=>name=e.PropertyName);a.Value=4;assert.equal(a.Value,4);assert.equal(name,'Value');});
test('for foreach if while switch return and break',()=>{const t=run('class A { public int Sum() { int total = 0; for (int i = 0; i < 5; i++) { total += i; } foreach (int n in new int[] { 1, 2, 3 }) { total += n; } while (total < 18) total++; switch (total) { case 18: return total; default: return -1; } } }');assert.equal(new t.A().Sum(),18);});
test('generic lists, LINQ lambdas and object initializers',()=>{const t=run('using System.Collections.Generic; using System.Linq; class A { public int Sum() { var values = new List<int> { 1, 2, 3, 4 }; return values.Where(x => x > 2).Sum(); } public A Make() { return new A { Value = 42 }; } public int Value { get; set; } }');assert.equal(new t.A().Sum(),7);assert.equal(new t.A().Make().Value,42);});
test('partial declarations merge and declaration order handles inheritance',()=>{const r=compileCSharp([{path:'a.cs',text:'partial class A : B { public int Get() => Value; } class B { public int Value {get;set;} = 9; }'},{path:'b.cs',text:'partial class A { public int Extra() => 4; }'}]);assert.equal(r.success,true,JSON.stringify(r.diagnostics));const types={};new Function('JB',r.code)({...DN,Object:DN.DotObject,defineType:(n,t)=>types[n]=t});assert.equal(new types.A().Get(),9);assert.equal(new types.A().Extra(),4);});
test('events invoke and handlers can unsubscribe with method groups',()=>{const t=run('class A { public event EventHandler Changed; public int Count; public void Handle(object sender, EventArgs e) { Count++; } public void Test() { Changed += Handle; Changed.Invoke(this, EventArgs.Empty); Changed -= Handle; Changed.Invoke(this, EventArgs.Empty); } }');const a=new t.A();a.Test();assert.equal(a.Count,1);});
test('async await returns real promises',async()=>{const t=run('class A { public async Task<int> Test() { await Task.Delay(1); return 42; } }');assert.equal(await new t.A().Test(),42);});
test('interpolation handles member expressions and formats',()=>{const t=run('class A { public string Test() { int n = 7; return $"Value {n:D3}, {{escaped}}"; } }');assert.equal(new t.A().Test(),'Value 007, {escaped}');});
test('try catch finally and exceptions',()=>{const t=run('class A { public int Value; public int Test() { try { throw new InvalidOperationException("bad"); } catch (InvalidOperationException e) { return e.Message.Length; } finally { Value = 2; } } }');const a=new t.A();assert.equal(a.Test(),3);assert.equal(a.Value,2);});
test('overloads dispatch by arity and default arguments are preserved',()=>{const t=run('class A { public int Sum(int a) => a; public int Sum(int a,int b) => a+b; public int Default(int n=3) => n; }');const a=new t.A();assert.equal(a.Sum(1),1);assert.equal(a.Sum(1,2),3);assert.equal(a.Default(),3);});
test('dictionary indexers and arrays enforce bounds',()=>{const t=run('class A { public int Test() { var d = new Dictionary<string,int>(); d["a"] = 9; var a = new int[] { 1, 2 }; a[0] = d["a"]; return a[0]; } }');assert.equal(new t.A().Test(),9);assert.throws(()=>DN.getIndex([1],1));});
test('unsupported features fail with diagnostic codes',()=>{for(const text of ['record R(int Value);','class A { public void M(ref int n) {} }','class A { decimal x; }','class A { void M() { lock(this) {} } }','class A { [ObservableProperty] string name; }','class A { void M(int x) {} void M(string x) {} }']){const r=compileCSharp(text);assert.equal(r.success,false,text);assert.equal(r.code,'');assert.ok(r.diagnostics.some(d=>d.severity==='error'));}});
test('unresolved identifiers are compiler errors',()=>assert.equal(compileCSharp('class A { int M() => Unknown; }').success,false));
test('integer overflow, division and banker rounding',()=>{assert.equal(DN.iadd(2147483647,1),-2147483648);assert.equal(DN.idiv(-5,2),-2);assert.throws(()=>DN.idiv(1,0),DN.DivideByZeroException);assert.equal(DN.MathApi.Round(2.5),2);assert.equal(DN.MathApi.Round(3.5),4);});

test('hexadecimal digits are not mistaken for float suffixes',()=>{const t=run('class A { public int Test() => 0xFF + 0xDD + 0b11; }');assert.equal(new t.A().Test(),479);assert.equal(lexCSharp("char a = 'ab';").diagnostics[0].code,'JB2002');});
