import test from 'node:test';
import assert from 'node:assert/strict';
import {editProperty,editExpression,reparentControl,inspectSource,EditHistory} from '../packages/development/designer.js';
import {compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
const cs=s=>`public class View:UserControl {public View(){Content=${s};}}`;
function run(source){const r=compileProject({'View.cs':source});assert.equal(r.success,true,JSON.stringify(r.diagnostics));const JB=createRuntime();new Function('JB',r.code)(JB);return new (JB.types.get('View'))();}
for(const init of ['new Button()','new Button { }','new Button {Content="x"}','new Button {Content="x",}'])test('initializer property insertion compiles and runs: '+init,()=>{const source=cs(init),r=editProperty(source,'View.cs',source.indexOf('new Button'),'Height','42.5'),view=run(r.after);assert.equal(view.Content.Height,42.5);view.Dispose();});
test('initializer removal preserves trivia and compiles for first middle last and only members',()=>{for(const property of ['Content','Width','Height']){const source=cs('new Button {Content="x", /*keep*/ Width=12, Height=34}'),r=editProperty(source,'View.cs',source.indexOf('new Button'),property,null);assert.match(r.after,/\/\*keep\*\//);const view=run(r.after);assert.equal(inspectSource(r.after,'View.cs',source.indexOf('new Button')).properties[property],undefined);view.Dispose();}const source=cs('new Button { /*a*/ Width /*b*/ = /*c*/ 12 /*d*/ }'),r=editProperty(source,'View.cs',source.indexOf('new Button'),'Width',null);for(const c of ['a','b','c','d'])assert.ok(r.after.includes('/*'+c+'*/'));run(r.after).Dispose();});
test('C# string escaping prevents executable or markup injection and preserves value',()=>{const source=cs('new Button {Content=@"old"}'),value='quote"\n</script> Ł 😀',r=editProperty(source,'View.cs',source.indexOf('new Button'),'Content',value),view=run(r.after);assert.equal(view.Content.Content,value);assert.doesNotMatch(r.after,/<\/script>/);view.Dispose();});
test('negative number and char edits keep their expression types',()=>{let source=cs('new TextBox {Width=-1,PasswordChar=\'x\'}'),at=source.indexOf('new TextBox');source=editProperty(source,'View.cs',at,'Width','-2').after;source=editProperty(source,'View.cs',at,'PasswordChar',"'").after;const view=run(source);assert.equal(view.Content.Width,-2);assert.equal(view.Content.PasswordChar,"'");view.Dispose();});
test('C# designer rejects expressions unknown properties invalid values and name mutations',()=>{const source=cs('new Button {Width=12+2}'),at=source.indexOf('new Button');for(const [p,v]of [['Width','10'],['Missing','x'],['Name','evil'],['Height','NaN'],['IsEnabled','yes'],['Padding','12'],['Click','Handler']])assert.throws(()=>editProperty(source,'View.cs',at,p,v));});
test('C# multiline additions keep CRLF comments and stale-preimage protection',()=>{const source=cs('new Button {\r\n Content="x", //keep\r\n }'),at=source.indexOf('new Button'),t=editProperty(source,'View.cs',at,'Width','33'),docs={'View.cs':source},history=new EditHistory();assert.match(t.after,/\/\/keep/);assert.doesNotMatch(t.after,/(?<!\r)\n/);history.apply(docs,t);run(t.after).Dispose();history.undo(docs);assert.equal(docs['View.cs'],source);history.redo(docs);docs['View.cs']+=' ';assert.throws(()=>history.undo(docs));});
test('explicit expression editor writes parsed bindings while literal editor protects them',()=>{let text='<TextBlock Text="literal"/>',t=editExpression(text,'V.axaml',0,'Text','{Binding Title, Mode=OneWay}');assert.match(t.after,/Mode=OneWay/);assert.throws(()=>editProperty(t.after,'V.axaml',0,'Text','oops'),/protected/);assert.throws(()=>editExpression(text,'V.axaml',0,'Text','{Unknown X}'));assert.doesNotMatch(editExpression(t.after,'V.axaml',0,'Text',null).after,/Text=/);});
const xaml=body=>`<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="V">${body}</UserControl>`;
test('XAML source reparent keeps exact child bytes and binding expressions',()=>{const child='<TextBox Name="Input" Text="{Binding Title}"/>',source=xaml(`<StackPanel Name="P">${child}<!--keep--><Border Name="Target"/></StackPanel>`),t=reparentControl(source,'V.axaml',source.indexOf(child),'Target');assert.equal(t.after.split(child).length,2);assert.match(t.after,/<!--keep-->/);assert.ok(t.after.indexOf('<Border')<t.after.indexOf(child));const r=compileProject({'V.axaml':t.after});assert.equal(r.success,true,JSON.stringify(r.diagnostics));});
test('reparent respects empty explicit content slot and refuses cycles occupied hosts namespace changes',()=>{const child='<TextBox Name="Input"/>',source=xaml(`<StackPanel Name="P">${child}<Border Name="Target"><Border.Child/></Border></StackPanel>`);assert.match(reparentControl(source,'V.axaml',source.indexOf(child),'Target').after,/<Border.Child>[\s\S]*<TextBox/);assert.throws(()=>reparentControl(source,'V.axaml',source.indexOf('<StackPanel'),'Target'),/cycle/);assert.throws(()=>reparentControl(source.replace('<Border.Child/>','<Button/>'),'V.axaml',source.indexOf(child),'Target'),/not empty/);assert.throws(()=>reparentControl(source.replace('Name="Target"','Name="Target" xmlns:z="using:Other"'),'V.axaml',source.indexOf(child),'Target'),/namespace/);});
