import test from 'node:test';
import assert from 'node:assert/strict';
import {compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {planReload,reloadScript} from '../packages/development/reload.js';
import {editProperty,insertControl,removeControl,moveControl,EditHistory} from '../packages/development/designer.js';
import {createSourceMap,vlq} from '../packages/development/source-map.js';
import {readWatch,snapshot} from '../packages/development/watch.js';
const files={
 'View.axaml':'<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="Demo.Main"><StackPanel Name="Panel"><TextBox Name="Input" Text="initial"/><TextBlock Name="Label" Text="Count"/><Button Name="Action" Content="Add" Click="Add"/></StackPanel></UserControl>',
 'Main.cs':'namespace Demo; public partial class Main : UserControl { public int count=0; public Main(){ InitializeComponent(); } public void Add(object s, RoutedEventArgs e){ count += 1; Label.Text = $"Count: {count}"; } public int Loop(int n){int result=0;for(int i=0;i<n;i++) result+=i;return result;} }'
};
function setup(input=files){const result=compileProject(input,{debug:true});assert.equal(result.success,true,JSON.stringify(result.diagnostics));const JB=createRuntime(),events=[];JB.enableDevelopment({debug:result.debug,nativeBreaks:false,report:(kind,value)=>events.push({kind,value})});new Function('JB',result.code)(JB);const root=JB.createFromXaml('Demo.Main');JB.root=root;return {JB,root,result,events};}
test('debug instrumentation preserves C# control flow and release strips points',()=>{const a=compileProject(files),b=setup();assert.equal(a.debug,undefined);assert.doesNotMatch(a.code,/@jb:|dev\?\.hit/);assert.match(b.result.code,/@jb:/);assert.equal(b.root.Loop(5),10);b.root.Action.raise('Click');assert.equal(b.root.count,1);b.root.Dispose();});
test('conditional and hit-count breakpoints capture actual locals without expression evaluation',()=>{const {JB,root,result,events}=setup(),point=result.debug.sites.find(p=>p.method.endsWith('.Loop')&&p.offset===files['Main.cs'].indexOf('result+=i'));
 assert.ok(point);JB.dev.configure({breakpoints:[{file:point.file,line:point.line,condition:'i == 3',hitCount:1}],watches:['i','result']});assert.equal(root.Loop(5),10);const hits=events.filter(e=>e.kind==='debug-hit');assert.ok(hits.some(h=>h.value.locals.i===3&&h.value.locals.result===3));root.Dispose();});
test('debug locations retain original lines through preprocessor and partial source files',()=>{const source='#if NEVER\nbad unsupported\n#endif\nnamespace Demo; public class A {\n public int Twice(int a) {\n return a*2;\n }\n}';const result=compileProject({'A.cs':source},{debug:true});assert.equal(result.success,true);assert.equal(result.debug.sites[0].line,6);assert.equal(result.debug.sites[0].file,'A.cs');});
test('source map encodes original UTF-16 source including Unicode',()=>{assert.equal(vlq(0),'A');assert.equal(vlq(-1),'D');const map=createSourceMap('/*@jb:0*/let x=1;\n/*@jb:1*/return x;',[{id:0,file:'Ł.cs',line:7,column:3},{id:1,file:'Ł.cs',line:8,column:1}],{'Ł.cs':'// ą 😀'});assert.equal(map.version,3);assert.equal(map.sourcesContent[0],'// ą 😀');assert.match(map.sources[0],/%C5%81/);assert.ok(map.mappings.includes(';'));});
test('watch expressions cannot invoke getters or access prototypes',()=>{let called=0;const o={a:[42],get secret(){called++;return 1;}};assert.equal(readWatch(o,'a[0]'),42);for(const p of ['secret','a.constructor','a[0]();','a.__proto__'])assert.throws(()=>readWatch(o,p));assert.equal(called,0);assert.equal(snapshot(o).secret,'[getter]');});
test('XAML literal edit preserves comments prefixes and surrounding whitespace',()=>{const text='<UserControl xmlns="https://github.com/avaloniaui">\r\n  <!--keep-->\r\n  <TextBlock Text=\'old\' />\r\n</UserControl>';const offset=text.indexOf('<TextBlock'),t=editProperty(text,'View.axaml',offset,'Text','A & "B"');assert.match(t.after,/<!--keep-->/);assert.match(t.after,/Text="A &amp; &quot;B&quot;"/);assert.equal(t.after.split('\r\n').length,4);});
test('designer protects bindings and rejects stale source transactions',()=>{const text='<TextBlock Text="{Binding Name}"/>',history=new EditHistory();assert.throws(()=>editProperty(text,'A.axaml',0,'Text','new'),/protected/);const doc={a:'before'};assert.throws(()=>history.apply(doc,{file:'a',before:'stale',after:'bad'}));assert.equal(doc.a,'before');});
test('designer palette insert remove reorder and undo redo are source transactions',()=>{const text='<StackPanel><!--keep--><Button Content="A"/><TextBlock Text="B"/></StackPanel>';const insert=insertControl(text,'A.axaml',0,'TextBox');assert.match(insert.after,/<TextBox/);const move=moveControl(text,'A.axaml',text.indexOf('<TextBlock'),'up');assert.ok(move.after.indexOf('<TextBlock')<move.after.indexOf('<Button'));assert.match(move.after,/<!--keep-->/);const remove=removeControl(text,'A.axaml',text.indexOf('<Button'));assert.doesNotMatch(remove.after,/<Button/);const docs={'A.axaml':text},history=new EditHistory();history.apply(docs,insert);history.undo(docs);assert.equal(docs['A.axaml'],text);history.redo(docs);assert.equal(docs['A.axaml'],insert.after);});
test('C# literal initializer design editing retains surrounding source and refuses expressions',()=>{const text='class A { void Build(){ var b=new Button {Content="original", Width=100+5}; }}',at=text.indexOf('new Button');const t=editProperty(text,'A.cs',at,'Content','updated');assert.equal(t.after,text.replace('original','updated'));assert.throws(()=>editProperty(text,'A.cs',at,'Width','200'));});
test('hot reload preserves root input state and existing event subscription while replacing method',()=>{const {JB,root,result}=setup();root.Input.Text='typed';root.Action.raise('Click');const input={...files,'View.axaml':files['View.axaml'].replace('Content="Add"','Content="Add ten"'),'Main.cs':files['Main.cs'].replace('count += 1','count += 10')};const next=compileProject(input,{debug:true}),plan=planReload(result,next);assert.equal(plan.compatible,true,JSON.stringify(plan.reasons));new Function('JB',reloadScript(plan,result,next,1).replace('(globalThis.Jailbreak)','(JB)'))(JB);root.Action.raise('Click');assert.equal(root.count,11);assert.equal(root.Input.Text,'typed');assert.equal(root.Action.Content,'Add ten');assert.equal(JB.root,root);assert.equal(JB.dev.revision,1);root.Dispose();});
test('incompatible constructor and structural XAML edits require restart',()=>{const {root,result}=setup();for(const input of [{...files,'Main.cs':files['Main.cs'].replace('count=0','count=2')},{...files,'View.axaml':files['View.axaml'].replace('<TextBox','<Slider')}]){const next=compileProject(input,{debug:true});assert.equal(planReload(result,next).compatible,false);}root.Dispose();});
test('live tree contains XAML source and bindings without leaking control instances',()=>{const {JB,root}=setup();const entry=JB.dev.tree().find(c=>c.name==='Action');assert.equal(entry.source.file,'View.axaml');assert.equal(JB.dev.inspect(entry.id).properties.Content.value,'Add');assert.doesNotThrow(()=>JSON.stringify(JB.dev.tree()));root.Dispose();});
test('reload preflight rejects stale revisions without partial mutation',()=>{const {JB,root,result}=setup(),next=compileProject({...files,'View.axaml':files['View.axaml'].replace('Content="Add"','Content="changed"')},{debug:true});const plan=planReload(result,next);assert.throws(()=>JB.dev.applyReload({...plan,revision:5},[]),/Stale/);assert.equal(root.Action.Content,'Add');assert.equal(JB.dev.revision,0);root.Dispose();});
test('failed property patch restores previous values methods and revision',()=>{const {JB,root,result}=setup(),next=compileProject({...files,'View.axaml':files['View.axaml'].replace('Text="Count"','Text="Changed" FontSize="18"'),'Main.cs':files['Main.cs'].replace('count += 1','count += 10')},{debug:true});const plan=planReload(result,next),original=root.Label.SetValue;root.Label.SetValue=function(key,value){if(key==='FontSize')throw new Error('simulated renderer failure');return original.call(this,key,value);};assert.throws(()=>new Function('JB',reloadScript(plan,result,next,1).replace('(globalThis.Jailbreak)','(JB)'))(JB),/simulated/);assert.equal(root.Label.Text,'Count');root.Action.raise('Click');assert.equal(root.count,1);assert.equal(JB.dev.revision,0);root.Dispose();});
test('XAML construction breakpoints and bound locations use original source lines',()=>{const result=compileProject(files,{debug:true}),events=[],JB=createRuntime();assert.ok(result.debug.xamlSites.some(s=>s.file==='View.axaml'));JB.enableDevelopment({debug:result.debug,nativeBreaks:false,breakpoints:[{file:'View.axaml',line:1}],report:(event,payload)=>events.push({event,payload})});new Function('JB',result.code)(JB);const root=JB.createFromXaml('Demo.Main');assert.equal(events.filter(e=>e.event==='debug-hit'&&e.payload.point.language==='xaml').length,5);root.Dispose();});
test('logpoints report without a pause and broken conditions do not alter execution',()=>{const {JB,root,result,events}=setup(),point=result.debug.sites.find(p=>p.method.endsWith('.Add'));JB.dev.configure({breakpoints:[{file:point.file,line:point.line,log:true},{file:point.file,line:point.line,condition:'this.constructor()'}]});root.Action.raise('Click');assert.equal(root.count,1);assert.ok(events.some(e=>e.kind==='debug-log'));assert.ok(events.some(e=>e.kind==='debug-condition-error'));assert.equal(events.some(e=>e.kind==='debug-hit'),false);root.Dispose();});
test('repeated reload updates source identity without accumulating handlers',()=>{const {JB,root,result}=setup();let old=result,input={...files};for(let i=1;i<=10;i++){input={...input,'View.axaml':files['View.axaml'].replace('Content="Add"',`Content="Add ${i}"`),'Main.cs':files['Main.cs'].replace('count += 1',`count += ${i}`)};const next=compileProject(input,{debug:true}),plan=planReload(old,next);assert.equal(plan.compatible,true);new Function('JB',reloadScript(plan,old,next,i).replace('(globalThis.Jailbreak)','(JB)'))(JB);root.Action.raise('Click');old=next;}assert.equal(root.count,55);assert.equal(root.Action.Content,'Add 10');const source=JB.dev.tree().find(c=>c.name==='Action').source;assert.equal(source.offset,input['View.axaml'].indexOf('<Button'));root.Dispose();});
test('debug exception instrumentation retains throw identity and reports original source',()=>{const input={'Throw.cs':'public class A {public static void Fail(Exception e) {throw e;} }'},result=compileProject(input,{debug:true}),JB=createRuntime(),events=[];JB.enableDevelopment({debug:result.debug,nativeBreaks:false,report:(event,data)=>events.push({event,data})});new Function('JB',result.code)(JB);const error=new JB.Exception('same instance');assert.throws(()=>JB.types.get('A').Fail(error),e=>e===error);assert.equal(events.find(e=>e.event==='debug-exception').data.point.file,'Throw.cs');});

test('source maps cover debugger hooks and executable statement lines',()=>{const map=createSourceMap('/*@jb:0*/if(JB.dev?.hit(0,()=>({}))){debugger;}\nreturn 42;',[{id:0,file:'Map.cs',line:3,column:1}],{'Map.cs':'class A {}'});assert.equal(map.mappings.split(';').length,2);assert.ok(map.mappings.split(';').every(Boolean));});
