import test from 'node:test';import assert from 'node:assert/strict';
import {DockLayout,floatRect,dockSizes,restoreDockLayout} from '../packages/workbench/dock-model.js';
import {createDebugContext} from '../packages/workbench/debug-context.js';
const windows=[{id:'solution',zone:'right'},{id:'properties',zone:'right-lower'},{id:'outline',zone:'right'},{id:'stack',zone:'bottom',mode:'hidden'},{id:'locals',zone:'bottom-right',mode:'hidden'},{id:'watch',zone:'bottom-right',mode:'hidden'},{id:'output',zone:'bottom'},{id:'problems',zone:'bottom'},{id:'toolbox',zone:'left',mode:'auto-hide'}];
test('restored docking data admits registered windows and bounded finite geometry only',()=>{const m=new DockLayout(windows,{version:1,sizes:{left:Infinity,right:-1,split:999},windows:{injected:{zone:'right'},solution:{zone:'invalid',mode:'invalid',rect:{width:Infinity,x:-10,y:999999}}},active:{right:'injected'}},{width:390,height:844});assert.equal(m.window('solution').zone,'right');assert.equal(m.window('solution').mode,'docked');assert.equal(m.state.sizes.split,80);assert.equal(m.state.sizes.right,230);assert.equal(m.window('solution').rect.x,0);assert.ok(m.window('solution').rect.y<844);assert.equal(m.state.active.right,'solution');assert.throws(()=>m.window('injected'));});
test('docking moves and reorders windows while repairing active tabs in previous groups',()=>{const m=new DockLayout(windows);m.activate('outline');m.move('outline','bottom','problems');assert.equal(m.state.active.right,'solution');assert.deepEqual(m.inZone('bottom'),['output','outline','problems']);assert.equal(m.state.active.bottom,'outline');m.move('outline','right','solution');assert.deepEqual(m.inZone('right'),['outline','solution']);});
test('float auto-hide close and reopen do not lose window identity or geometry',()=>{const m=new DockLayout(windows);m.setMode('properties','floating');m.floating('properties',{x:40,y:80,width:330,height:210},{width:800,height:600});m.setMode('properties','hidden');m.activate('properties');assert.equal(m.window('properties').mode,'docked');assert.equal(m.window('properties').rect.x,40);m.setMode('properties','auto-hide');assert.equal(m.inZone('right-lower').length,0);assert.equal(m.state.active['right-lower'],null);});
test('snapshots do not alias model data and named layouts restore independent state',()=>{const m=new DockLayout(windows),snapshot=m.snapshot();snapshot.windows.solution.mode='hidden';assert.equal(m.window('solution').mode,'docked');m.restore(snapshot);snapshot.windows.solution.mode='floating';assert.equal(m.window('solution').mode,'hidden');});
test('all built-in presets keep their debugger designer and solution windows reachable',()=>{const m=new DockLayout(windows);m.preset('debug');assert.equal(m.state.active.bottom,'stack');assert.equal(m.state.active['bottom-right'],'locals');m.preset('design');assert.equal(m.state.active.right,'outline');assert.equal(m.window('toolbox').mode,'docked');m.preset('binary');assert.equal(m.window('properties').mode,'hidden');m.preset('code');assert.equal(m.window('solution').mode,'docked');assert.throws(()=>m.preset('unknown'));});
test('invalid commands and registered ID collisions do not overwrite model data',()=>{const m=new DockLayout(windows),before=m.snapshot();assert.throws(()=>m.move('solution','none'));assert.throws(()=>m.resize('right','300px'));assert.throws(()=>m.setMode('solution','bogus'));assert.deepEqual(before,m.snapshot());assert.throws(()=>new DockLayout([...windows,{id:'solution'}]));assert.throws(()=>new DockLayout([{id:'__proto__'}]));assert.ok(floatRect({}, {width:240,height:180}).height<=180);assert.equal(dockSizes(null).split,52);});
function session(){const listeners=new Set(),calls=[];let paused=null;return {calls,state:()=>({paused}),options:()=>({}),subscribe(fn){listeners.add(fn);return ()=>listeners.delete(fn);},command(...args){calls.push(args);},pause(value){paused=value;for(const l of listeners)l({event:'debug-paused',payload:value});},listeners};}
test('shared debugger context forwards only the selected session and replays its own pause',()=>{const source=session(),binary=session(),context=createDebugContext(source,binary),events=[];context.subscribe(e=>events.push(e));source.pause({taskId:1});binary.pause({taskId:2});assert.deepEqual(events.map(e=>e.payload.taskId),[1]);context.select('binary');assert.equal(context.state().paused.taskId,2);context.command('over');assert.deepEqual(binary.calls,[['over']]);assert.deepEqual(source.calls,[]);source.pause({taskId:3});assert.equal(events.at(-1).payload.taskId,2);context.select('source');assert.equal(events.at(-1).payload.taskId,3);context.dispose();assert.equal(source.listeners.size,0);assert.equal(binary.listeners.size,0);});
