import test from 'node:test';
import assert from 'node:assert/strict';
import {compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {planReload,reloadScript} from '../packages/development/reload.js';
import {applyStyles} from '../packages/avalonia-runtime/styling.js';
const wrap=body=>`<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="V">${body}</UserControl>`;
const cs='public partial class V:UserControl { public int count=0; public void A(object s,RoutedEventArgs e){count++;} public void B(object s,RoutedEventArgs e){count+=10;} }';
function compile(body){const r=compileProject({'V.axaml':wrap(body),'V.cs':cs},{debug:true});assert.equal(r.success,true,JSON.stringify(r.diagnostics));return r;}
function setup(body){const result=compile(body),JB=createRuntime();JB.enableDevelopment({debug:result.debug,nativeBreaks:false});new Function('JB',result.code)(JB);JB.root=JB.createFromXaml('V');const model=new JB.ObservableObject();model.First='one';model.Second='two';JB.root.DataContext=model;return {JB,root:JB.root,result,model};}
function reload(f,body){const next=compile(body),plan=planReload(f.result,next);assert.equal(plan.compatible,true,plan.reasons.join('; '));new Function('JB',reloadScript(plan,f.result,next,f.JB.dev.revision+1).replace('(globalThis.Jailbreak)','(JB)'))(f.JB);f.result=next;return plan;}
const input=path=>`<TextBox Name="Input" Text="{Binding ${path}}"/>`;
test('binding path replacement disconnects the old path and supports TwoWay without duplicate subscriptions',()=>{const f=setup(input('First')),c=f.root.Input;for(let i=0;i<12;i++){reload(f,input(i%2?'First':'Second'));assert.equal(f.root.Input,c);assert.equal(f.model.PropertyChanged.Count,1);}c.Text='edit';assert.equal(f.model.First,'edit');assert.equal(f.model.Second,'two');assert.equal(c._disposables.length,2);f.root.Dispose();assert.equal(f.model.PropertyChanged.Count,0);});
test('binding add/remove and literal replacement tear down subscriptions',()=>{const f=setup('<TextBox Name="Input" Text="literal"/>');reload(f,input('First'));assert.equal(f.root.Input.Text,'one');reload(f,'<TextBox Name="Input" Text="done"/>');assert.equal(f.model.PropertyChanged.Count,0);assert.equal(f.root.Input.Text,'done');reload(f,'<TextBox Name="Input"/>');assert.equal(f.root.Input.Text,'');f.root.Dispose();});
test('binding mode changes and OneTime context refresh obey selected direction',()=>{const f=setup(input('First, Mode=OneWay'));f.root.Input.Text='local';assert.equal(f.model.First,'one');reload(f,input('Second, Mode=OneTime'));f.model.Second='ignored';assert.equal(f.root.Input.Text,'two');const model=new f.JB.ObservableObject();model.Second='new context';f.root.DataContext=model;assert.equal(f.root.Input.Text,'new context');f.root.Dispose();});
test('failed binding reload restores old values and live subscriptions',()=>{const f=setup(input('First'));let n=0;const flush=f.JB.flushLayout;f.JB.flushLayout=()=>{if(!n++)throw new Error('render failed');flush();};assert.throws(()=>reload(f,input('Second')),/render failed/);assert.equal(f.root.Input.Text,'one');f.root.Input.Text='old path';assert.equal(f.model.First,'old path');assert.equal(f.model.Second,'two');assert.equal(f.model.PropertyChanged.Count,1);assert.equal(f.JB.dev.revision,0);f.root.Dispose();});
test('new bound subtrees resolve sibling names after all staged fragments attach',()=>{const f=setup('<StackPanel Name="P"/>');reload(f,'<StackPanel Name="P"><TextBlock Name="Label" Text="{Binding Text, ElementName=NewInput}"/><TextBox Name="NewInput" Text="linked"/></StackPanel>');assert.equal(f.root.Label.Text,'linked');f.root.NewInput.Text='live';assert.equal(f.root.Label.Text,'live');f.root.Dispose();});
test('live event rewiring replaces only the XAML-owned subscription',()=>{const f=setup('<Button Name="Button" Click="A"/>');let extra=0;f.root.Button.Click.add(()=>extra++);reload(f,'<Button Name="Button" Click="B"/>');f.root.Button.raise('Click');assert.equal(f.root.count,10);assert.equal(extra,1);reload(f,'<Button Name="Button"/>');f.root.Button.raise('Click');assert.equal(f.root.count,10);assert.equal(extra,2);f.root.Dispose();});
const resources=(color,styles='')=>`<UserControl.Resources><SolidColorBrush x:Key="Accent" Color="${color}"/></UserControl.Resources>${styles}<StackPanel><TextBlock Name="Dynamic" Foreground="{DynamicResource Accent}"/><TextBlock Name="Static" Foreground="{StaticResource Accent}"/><TextBox Name="Input"/></StackPanel>`;
test('resource dictionary identity is retained and dynamic/static resource semantics stay distinct',()=>{const f=setup(resources('Red')),dict=f.root.Resources,staticBrush=f.root.Static.Foreground;f.root.Input.Text='typed';reload(f,resources('Blue'));assert.equal(f.root.Resources,dict);assert.equal(f.root.Dynamic.Foreground.Color.value,'Blue');assert.equal(f.root.Static.Foreground,staticBrush);assert.equal(staticBrush.Color.value,'Red');assert.equal(f.root.Input.Text,'typed');f.root.Dispose();});
test('failed resource patch restores dictionary values and dynamic subscriptions',()=>{const f=setup(resources('Red')),dict=f.root.Resources,brush=f.root.Dynamic.Foreground;let n=0;const flush=f.JB.flushLayout;f.JB.flushLayout=()=>{if(!n++)throw new Error('render failed');flush();};assert.throws(()=>reload(f,resources('Blue')),/render failed/);assert.equal(f.root.Resources,dict);assert.equal(dict.get('Accent'),brush);assert.equal(f.root.Dynamic.Foreground,brush);assert.equal(f.JB.dev.revision,0);f.root.Dispose();});
test('dynamic resource path follows reparenting and detaches old dictionaries',()=>{const body=side=>`<StackPanel><Border Name="Left"><Border.Resources><SolidColorBrush x:Key="Accent" Color="Red"/></Border.Resources>${side==='left'?'<TextBlock Name="Label" Foreground="{DynamicResource Accent}"/>':''}</Border><Border Name="Right"><Border.Resources><SolidColorBrush x:Key="Accent" Color="Blue"/></Border.Resources>${side==='right'?'<TextBlock Name="Label" Foreground="{DynamicResource Accent}"/>':''}</Border></StackPanel>`,f=setup(body('left')),c=f.root.Label;reload(f,body('right'));assert.equal(f.root.Label,c);assert.equal(c.Foreground.Color.value,'Blue');f.root.Left.Resources.set('Accent','Green');assert.equal(c.Foreground.Color.value,'Blue');f.root.Right.Resources.set('Accent','Purple');assert.equal(c.Foreground,'Purple');f.root.Dispose();});
test('style replacement respects local value priority and removes obsolete setters',()=>{const body=size=>`<UserControl.Styles><Style Selector="TextBlock"><Setter Property="FontSize" Value="${size}"/></Style></UserControl.Styles><StackPanel><TextBlock Name="Styled"/><TextBlock Name="Local" FontSize="44"/></StackPanel>`,f=setup(body(12));applyStyles(f.root.Styled);applyStyles(f.root.Local);reload(f,body(24));applyStyles(f.root.Styled);applyStyles(f.root.Local);assert.equal(f.root.Styled.FontSize,24);assert.equal(f.root.Local.FontSize,44);reload(f,'<StackPanel><TextBlock Name="Styled"/><TextBlock Name="Local" FontSize="44"/></StackPanel>');applyStyles(f.root.Styled);assert.equal(f.root.Styled.FontSize,null);f.root.Dispose();});
test('direct control-template replacement retains owner and disposes old template scope',()=>{const body=text=>`<Button Name="Owner" Content="borrowed"><Button.Template><ControlTemplate><Border><TextBlock Name="PART_Label" Text="${text}"/></Border></ControlTemplate></Button.Template></Button>`,f=setup(body('one')),owner=f.root.Owner;owner.ApplyTemplate();const part=owner._templateInstance.names.get('PART_Label');reload(f,body('two'));owner.ApplyTemplate();assert.equal(f.root.Owner,owner);assert.equal(owner._templateInstance.names.get('PART_Label').Text,'two');assert.equal(part._disposed,true);assert.equal(f.root.FindControl('PART_Label'),null);f.root.Dispose();});
test('failed template update retains exact old part identity',()=>{const body=text=>`<Button Name="Owner"><Button.Template><ControlTemplate><TextBlock Name="PART_Label" Text="${text}"/></ControlTemplate></Button.Template></Button>`,f=setup(body('old')),owner=f.root.Owner;owner.ApplyTemplate();const old=owner._templateInstance,flush=f.JB.flushLayout;let n=0;f.JB.flushLayout=()=>{if(!n++){owner.ApplyTemplate();throw new Error('render failed');}flush();};assert.throws(()=>reload(f,body('new')),/render failed/);assert.equal(owner._templateInstance,old);assert.equal(old.root._disposed,false);assert.equal(f.JB.dev.revision,0);f.root.Dispose();});
test('resource or attribute failures do not leak new observers',()=>{const f=setup(input('First')),before=f.model.PropertyChanged.Count;assert.throws(()=>reload(f,input('Second, Converter={StaticResource Missing}')),/not found/);assert.equal(f.model.PropertyChanged.Count,before);assert.equal(f.root.Input.Text,'one');f.root.Dispose();});
