import test from 'node:test';
import assert from 'node:assert/strict';
import {Workspace,normalizePath,readSolution,readProject,compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {StyledObject,AvaloniaProperty,observePath} from '../packages/avalonia-runtime/properties.js';
import {ObservableObject} from '../packages/dotnet-runtime/index.js';
const files={
 'Demo.csproj':'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>',
 'Main.axaml':'<Window xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="Demo.Main"><StackPanel><TextBox x:Name="Input" Text="{Binding Name}"/><TextBlock x:Name="Greeting" Text="{Binding Name}"/><TextBlock x:Name="Number" Text="{Binding Count}"/><Button x:Name="Add" Click="OnAdd">Add</Button></StackPanel></Window>',
 'Main.axaml.cs':'using Avalonia.Controls; namespace Demo; public partial class Main : Window { public string Name {get;set;} = "Ada"; public int Count {get;set;} public Main(){InitializeComponent();DataContext=this;} void OnAdd(object sender, RoutedEventArgs e){Count++;} }'
};
function compile(input=files){const r=compileProject(input);assert.equal(r.success,true,JSON.stringify(r.diagnostics));const JB=createRuntime();new Function('JB',r.code)(JB);return {r,JB};}
test('workspace rejects traversal, normalizes project-relative paths and preserves source',()=>{assert.throws(()=>normalizePath('../secret'));assert.throws(()=>normalizePath('/a'));assert.equal(normalizePath('a/../b.cs'),'b.cs');assert.equal(new Workspace(files).get('Main.axaml.cs'),files['Main.axaml.cs']);});
test('solution and project reference graph compile into one registration unit',()=>{const source={'Demo.sln':'Project("{A}") = "App", "App\\App.csproj", "{B}"\nEndProject','App/App.csproj':'<Project><ItemGroup><ProjectReference Include="../Lib/Lib.csproj"/></ItemGroup></Project>','App/A.cs':'class A : B {}','Lib/Lib.csproj':'<Project/>','Lib/B.cs':'class B {}'};const ws=new Workspace(source);assert.deepEqual(readSolution(ws,'Demo.sln').projects,['App/App.csproj']);const r=compileProject(ws);assert.equal(r.success,true,JSON.stringify(r.diagnostics));assert.equal(r.types.length,2);});
test('missing references and cycles are errors, not false successful builds',()=>{assert.equal(compileProject({'A.csproj':'<Project><ItemGroup><ProjectReference Include="B.csproj"/></ItemGroup></Project>'}).success,false);assert.equal(compileProject({'A.csproj':'<Project><ItemGroup><ProjectReference Include="A.csproj"/></ItemGroup></Project>'}).success,false);});
test('Compile Remove and default source exclusion',()=>{const w=new Workspace({'A.csproj':'<Project><ItemGroup><Compile Remove="Skip.cs"/></ItemGroup></Project>','A.cs':'class A {}','Skip.cs':'nonsense','obj/G.cs':'nonsense'});assert.deepEqual(readProject(w,'A.csproj').sources,['A.cs']);assert.equal(compileProject(w).success,true);});
test('compiled C# hydrates XAML names, binds inherited context and invokes real handlers',()=>{const {JB}=compile();const root=new (JB.types.get('Demo.Main'))();assert.equal(root.Input.Text,'Ada');root.Input.Text='Grace';assert.equal(root.Name,'Grace');assert.equal(root.Greeting.Text,'Grace');root.Add.raise('Click');assert.equal(root.Count,1);assert.equal(root.Number.Text,1);root.Dispose();assert.equal(root.PropertyChanged.Count,0);});
test('XAML without code-behind produces a generated partial class',()=>{const {JB}=compile({'Main.axaml':'<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="Main"><TextBlock x:Name="Text" Text="Hello"/></UserControl>'});const root=new (JB.types.get('Main'))();assert.equal(root.Text.Text,'Hello');root.Dispose();});
test('property precedence and clear restore styles and defaults',()=>{const p=AvaloniaProperty.Register(StyledObject,'Value',4),o=new StyledObject();o.SetValue(p,10,100);o.SetValue(p,20);assert.equal(o.GetValue(p),20);o.ClearValue(p);assert.equal(o.GetValue(p),10);o.ClearValue(p,100);assert.equal(o.GetValue(p),4);});
test('binding path graph detaches old intermediate objects',()=>{const a=new ObservableObject(),b=new ObservableObject(),model=new ObservableObject();a.Value='A';b.Value='B';model.Child=a;const values=[];const off=observePath(model,'Child.Value',v=>values.push(v));model.Child=b;model.RaisePropertyChanged('Child');a.Value='old';a.RaisePropertyChanged('Value');b.Value='new';b.RaisePropertyChanged('Value');assert.deepEqual(values,['A','B','new']);off();assert.equal(model.PropertyChanged.Count,0);assert.equal(b.PropertyChanged.Count,0);});
test('resources, dynamic updates and data templates instantiate separate controls',()=>{const {JB}=compile({'Page.axaml':'<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="Page"><UserControl.Resources><SolidColorBrush x:Key="Accent" Color="Blue"/></UserControl.Resources><StackPanel><TextBlock x:Name="Title" Foreground="{DynamicResource Accent}" Text="Hi"/><ItemsControl x:Name="List"><ItemsControl.ItemTemplate><DataTemplate><TextBlock Text="{Binding Name}"/></DataTemplate></ItemsControl.ItemTemplate></ItemsControl></StackPanel></UserControl>'});const root=new (JB.types.get('Page'))();assert.equal(root.Title.Foreground.toString(),'Blue');root.Resources.set('Accent','Red');assert.equal(root.Title.Foreground,'Red');const a=root.List.ItemTemplate.build({Name:'A'},root.List),b=root.List.ItemTemplate.build({Name:'B'},root.List);assert.notEqual(a,b);assert.equal(a.Text,'A');assert.equal(b.Text,'B');a.Dispose();b.Dispose();root.Dispose();});
