import test from 'node:test';
import assert from 'node:assert/strict';
import {compileXaml} from '../packages/xaml-compiler/index.js';
import {compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {ResourceDictionary} from '../packages/avalonia-runtime/properties.js';
import {parseSelector,matches} from '../packages/avalonia-runtime/selectors.js';
const ns='xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"';
function setup(files){const result=compileProject(files);assert.equal(result.success,true,JSON.stringify(result.diagnostics));const JB=createRuntime();new Function('JB',result.code)(JB);const root=JB.createFromXaml(result.manifest.entryXaml);return{JB,root,result};}
function page(body,resources=''){return `<UserControl ${ns}>${resources?'<UserControl.Resources>'+resources+'</UserControl.Resources>':''}<StackPanel>${body}</StackPanel></UserControl>`;}
const template='<ControlTemplate><Border Name="PART_Chrome"><TextBlock Name="PART_Label" Text="{TemplateBinding Content}"/></Border></ControlTemplate>';

test('merged dictionaries choose local then last merged and notify on remove',()=>{const a=new ResourceDictionary([['Color','red']]),b=new ResourceDictionary([['Color','blue']]),d=new ResourceDictionary();const changes=[];d.subscribe(k=>changes.push(k));d.MergedDictionaries.Add(a);d.MergedDictionaries.Add(b);assert.equal(d.get('Color'),'blue');d.Add('Color','green');assert.equal(d.get('Color'),'green');d.delete('Color');assert.equal(d.get('Color'),'blue');d.MergedDictionaries.Remove(b);assert.equal(d.get('Color'),'red');a.set('Color','pink');assert.equal(d.get('Color'),'pink');assert.deepEqual([...d.keys()],['Color']);assert.equal(d.Count,1);assert.ok(changes.length>=6);d.Dispose();assert.equal(a.listeners.size,0);});
test('merged resource cycles and duplicate instances fail',()=>{const a=new ResourceDictionary(),b=new ResourceDictionary();a.MergedDictionaries.Add(b);assert.throws(()=>b.MergedDictionaries.Add(a),/cycle/);assert.throws(()=>a.MergedDictionaries.Add(b),/Duplicate/);assert.throws(()=>a.MergedDictionaries.Add(a),/cycle/);});
test('deferred resources instantiate once, support forward references and reject cycles',()=>{const d=new ResourceDictionary();let calls=0;d.defer('A',()=>{calls++;return d.get('B')});d.defer('B',()=>42);assert.equal(d.get('A'),42);assert.equal(d.get('A'),42);assert.equal(calls,1);d.defer('C',()=>d.get('D'));d.defer('D',()=>d.get('C'));assert.throws(()=>d.get('C'),/Cyclic/);assert.equal(d.has('C'),true);});
test('dictionary delete and clear send invalidations without evaluating lazy values',()=>{const d=new ResourceDictionary(),events=[];d.defer('lazy',()=>{throw Error('must not materialize');});d.subscribe(k=>events.push(k));d.clear();assert.deepEqual(events,['lazy']);});
test('template part names are private and repeated instances bind independently',()=>{const {root}=setup({'View.axaml':page('<Button Name="A" Content="one" Template="{StaticResource Card}"/><Button Name="B" Content="two" Template="{StaticResource Card}"/>',template.replace('<ControlTemplate>','<ControlTemplate x:Key="Card">'))});const a=root.FindControl('A'),b=root.FindControl('B');assert.equal(root.FindControl('PART_Label'),null);a.ApplyTemplate();b.ApplyTemplate();const la=a.FindTemplateChild('PART_Label'),lb=b.FindTemplateChild('PART_Label');assert.notEqual(la,lb);assert.equal(la.Text,'one');assert.equal(lb.Text,'two');a.Content='three';assert.equal(la.Text,'three');assert.equal(lb.Text,'two');assert.equal(root.PART_Label,undefined);root.Dispose();});
test('TemplateBinding is one way and does not replace inherited DataContext',()=>{const {root}=setup({'View.axaml':page(`<Button Name="A" Content="one"><Button.Template>${template}</Button.Template></Button>`)});root.DataContext={Caption:'vm'};const a=root.FindControl('A');a.ApplyTemplate();const label=a.FindTemplateChild('PART_Label');assert.equal(label.DataContext,root.DataContext);assert.equal(label.TemplatedParent,a);label.Text='local';assert.equal(a.Content,'one');root.Dispose();});
test('explicit RelativeSource TemplatedParent supports two-way bindings',()=>{const {root}=setup({'View.axaml':page('<ContentControl Name="Owner" Content="one"><ContentControl.Template><ControlTemplate><TextBox Name="Editor" Text="{Binding Content, RelativeSource={RelativeSource TemplatedParent}, Mode=TwoWay}"/></ControlTemplate></ContentControl.Template></ContentControl>')});const owner=root.FindControl('Owner');owner.ApplyTemplate();const editor=owner.FindTemplateChild('Editor');assert.equal(editor.Text,'one');editor.Text='two';assert.equal(owner.Content,'two');owner.Content='three';assert.equal(editor.Text,'three');root.Dispose();});
test('replacement releases subscriptions and leaves no old namescope',()=>{const {root}=setup({'View.axaml':page(`<Button Name="A" Content="one"><Button.Template>${template}</Button.Template></Button>`)});const a=root.FindControl('A');a.ApplyTemplate();const old=a.FindTemplateChild('PART_Label'),count=a.PropertyChanged.Count;a.Template={kind:'controlTemplate',build(owner){return{root:new owner.constructor('Control'),names:new Map()};}};a.ApplyTemplate();assert.equal(old._disposed,true);assert.equal(a.FindTemplateChild('PART_Label'),null);assert.equal(a.PropertyChanged.Count,count-1);root.Dispose();});
test('failed template replacement leaves old tree intact',()=>{const {root}=setup({'View.axaml':page(`<Button Name="A"><Button.Template>${template}</Button.Template></Button>`)});const a=root.FindControl('A');a.ApplyTemplate();const old=a.FindTemplateChild('PART_Label');a.Template={kind:'controlTemplate',build(){throw Error('bad template');}};assert.throws(()=>a.ApplyTemplate(),/bad template/);assert.equal(a.FindTemplateChild('PART_Label'),old);assert.equal(old._disposed,false);root.Dispose();});
test('names inside DataTemplates are not exported to page code-behind',()=>{const {root}=setup({'View.axaml':page('<ItemsControl Name="Repeater"><ItemsControl.ItemTemplate><DataTemplate><TextBlock Name="SameName" Text="{Binding Caption}"/></DataTemplate></ItemsControl.ItemTemplate></ItemsControl>')});const list=root.FindControl('Repeater'),a=list.ItemTemplate.build({Caption:'one'},list),b=list.ItemTemplate.build({Caption:'two'},list);assert.equal(root.SameName,undefined);assert.notEqual(a,b);assert.equal(a.Text,'one');assert.equal(b.Text,'two');a.Dispose();b.Dispose();root.Dispose();});
test('template body and TemplateBinding constraints are compile errors',()=>{for(const body of ['<TextBlock Text="{TemplateBinding Content}"/>','<Button><Button.Template><ControlTemplate><Border/><Border/></ControlTemplate></Button.Template></Button>','<Button><Button.Template><ControlTemplate><TextBlock Text="{TemplateBinding Content.Length}"/></ControlTemplate></Button.Template></Button>','<Button><Button.Template><ControlTemplate><TextBlock Text="{TemplateBinding Content, Mode=TwoWay}"/></ControlTemplate></Button.Template></Button>']){assert.equal(compileXaml(page(body)).success,false,body);}});
test('theme resources support forward BasedOn references and local precedence',()=>{const themes='<ControlTheme x:Key="Derived" TargetType="Button" BasedOn="{StaticResource Base}"><Setter Property="Padding" Value="18"/></ControlTheme><ControlTheme x:Key="Base" TargetType="Button"><Setter Property="Foreground" Value="Red"/><Setter Property="Template">'+template.replace('<ControlTemplate>','<Setter.Value><ControlTemplate>').replace('</ControlTemplate>','</ControlTemplate></Setter.Value>')+'</Setter></ControlTheme>';const {root}=setup({'View.axaml':page('<Button Name="A" Content="themed" Theme="{StaticResource Derived}" Foreground="Blue"/>',themes)});const a=root.FindControl('A');a.ApplyTemplate();assert.equal(a.Foreground,'Blue');assert.equal(a.Padding,'18');assert.equal(a.FindTemplateChild('PART_Label').Text,'themed');a.Theme=null;a.ApplyTemplate();assert.equal(a.Template,null);assert.equal(a.FindTemplateChild('PART_Label'),null);root.Dispose();});
test('type-keyed themes apply implicitly to matching controls',()=>{const {root}=setup({'View.axaml':page('<Button Name="A"/>','<ControlTheme x:Key="{x:Type Button}" TargetType="Button"><Setter Property="Foreground" Value="Red"/></ControlTheme>')});const a=root.FindControl('A');a.ApplyTemplate();assert.equal(a.Foreground,'Red');root.Dispose();});
test('ResourceInclude and StyleInclude link selected files without runtime network',()=>{const files={'App/App.csproj':'<Project/>','App/Views/View.axaml':page('<Button Name="A" Content="linked"/>','<ResourceDictionary><ResourceDictionary.MergedDictionaries><ResourceInclude Source="../Themes/Colors.axaml"/></ResourceDictionary.MergedDictionaries></ResourceDictionary>').replace('<StackPanel>','<UserControl.Styles><StyleInclude Source="avares://App/Themes/Styles.axaml"/></UserControl.Styles><StackPanel>'),'App/Themes/Colors.axaml':`<ResourceDictionary ${ns}><SolidColorBrush x:Key="Accent" Color="Blue"/></ResourceDictionary>`,'App/Themes/Styles.axaml':`<Styles ${ns}><Style Selector="Button"><Setter Property="Template"><Setter.Value>${template}</Setter.Value></Setter></Style></Styles>`};const {root,result}=setup(files);assert.equal(result.manifest.xamlIncludes.length,2);assert.equal(root.Resources.get('Accent').Color.toString(),'Blue');assert.equal(root.Styles.length,1);root.Dispose();});
test('include errors retain source file locations and block executable output',()=>{for(const source of ['Missing.axaml','https://example.com/x.axaml','avares://Unknown/a.axaml','../../secret.axaml']){const result=compileProject({'View.axaml':`<UserControl ${ns}>\n<UserControl.Styles><StyleInclude Source="${source}"/></UserControl.Styles></UserControl>`});assert.equal(result.success,false);assert.equal(result.code,'');const d=result.diagnostics.find(d=>d.code==='JB1120');assert.equal(d.file,'View.axaml');assert.equal(d.line,2);}});
test('include graph cycles and wrong root types fail before runtime',()=>{const result=compileProject({'A.axaml':`<Styles ${ns}><StyleInclude Source="B.axaml"/></Styles>`,'B.axaml':`<Styles ${ns}><StyleInclude Source="A.axaml"/></Styles>`});assert.ok(result.diagnostics.some(d=>d.code==='JB1121'));const bad=compileProject({'A.axaml':`<Styles ${ns}><StyleInclude Source="B.axaml"/></Styles>`,'B.axaml':`<ResourceDictionary ${ns}/>`});assert.ok(bad.diagnostics.some(d=>d.code==='JB1120'));});
test('dynamic resources react through merged dictionaries and restore on deletion',()=>{const {root}=setup({'View.axaml':page('<TextBlock Name="Label" Foreground="{DynamicResource Accent}"/>','<ResourceDictionary><ResourceDictionary.MergedDictionaries><ResourceDictionary><SolidColorBrush x:Key="Accent" Color="Red"/></ResourceDictionary></ResourceDictionary.MergedDictionaries></ResourceDictionary>')});const label=root.FindControl('Label'),merged=[...root.Resources.MergedDictionaries][0];assert.equal(label.Foreground.toString(),'Red');merged.set('Accent','Blue');assert.equal(label.Foreground,'Blue');root.Resources.set('Accent','Green');assert.equal(label.Foreground,'Green');root.Resources.delete('Accent');assert.equal(label.Foreground,'Blue');root.Dispose();assert.equal(merged.listeners.size,0);});
test('strict selector parser rejects syntax previously silently ignored',()=>{for(const s of ['Button >> Border','Button:not(.x)','Button[Foo=true]','^:checked','Button /template/','Button,'])assert.throws(()=>parseSelector(s));assert.doesNotThrow(()=>parseSelector('Button.primary:pointerover /template/ Border#PART_Chrome, Grid > TextBlock'));});
test('template selector axes do not cross namescope boundaries accidentally',()=>{const owner={type:'Button',Classes:'primary',pseudos:new Set(['pointerover'])},part={type:'Border',Name:'PART',parent:owner,TemplatedParent:owner,pseudos:new Set()};assert.equal(matches(part,'Button:pointerover /template/ Border#PART'),true);assert.equal(matches(part,'Button Border'),false);assert.equal(matches(part,'Button > Border'),false);});
test('compiled OnApplyTemplate can resolve parts and subscribe handlers',()=>{const {root}=setup({'View.axaml':`<UserControl ${ns} xmlns:local="using:Demo"><local:Card Name="A"><local:Card.Template><ControlTemplate><Button Name="PART_Click">Hit</Button></ControlTemplate></local:Card.Template></local:Card></UserControl>`,'Card.cs':'namespace Demo; public class Card : TemplatedControl { public int Count {get;set;} protected override void OnApplyTemplate(TemplateAppliedEventArgs e) { base.OnApplyTemplate(e); var button=e.NameScope.Find<Button>("PART_Click"); button.Click += (s,args) => Count++; } }'});const card=root.FindControl('A');card.ApplyTemplate();card.FindTemplateChild('PART_Click').raise('Click');assert.equal(card.Count,1);root.Dispose();});
test('template target constraints fail explicitly at application time',()=>{const {root}=setup({'View.axaml':page('<ContentControl Name="Card" Template="{StaticResource ButtonOnly}"/>','<ControlTemplate x:Key="ButtonOnly" TargetType="Button"><Border/></ControlTemplate>')});assert.throws(()=>root.FindControl('Card').ApplyTemplate(),/TargetType mismatch/);root.Dispose();});
test('input templates without a host adapter and bound setters are rejected',()=>{for(const body of ['<TextBox><TextBox.Template><ControlTemplate><Border/></ControlTemplate></TextBox.Template></TextBox>','<UserControl.Styles><Style Selector="Button"><Setter Property="Content" Value="{Binding Caption}"/></Style></UserControl.Styles>'])assert.equal(compileXaml(page(body)).success,false);});
