import test from 'node:test';
import assert from 'node:assert/strict';
import {compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {planReload,reloadScript} from '../packages/development/reload.js';
const cs='public partial class V:UserControl { public int count=0; public void Go(object s,RoutedEventArgs e){count++;} }';
const doc=body=>`<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="V">${body}</UserControl>`;
function build(body){const r=compileProject({'V.axaml':doc(body),'V.cs':cs},{debug:true});assert.equal(r.success,true,JSON.stringify(r.diagnostics));return r;}
function setup(body){const result=build(body),JB=createRuntime();JB.enableDevelopment({debug:result.debug,nativeBreaks:false});new Function('JB',result.code)(JB);JB.root=JB.createFromXaml('V');return {JB,root:JB.root,result};}
function reload(f,body){const next=build(body),plan=planReload(f.result,next);assert.equal(plan.compatible,true,plan.reasons.join('; '));new Function('JB',reloadScript(plan,f.result,next,f.JB.dev.revision+1).replace('(globalThis.Jailbreak)','(JB)'))(f.JB);f.result=next;return plan;}
const row=(a,b)=>`<StackPanel Name="P"><StackPanel Name="A">${a}</StackPanel><Border Name="B">${b}</Border></StackPanel>`;
test('content-host replacement keeps the host and disposes only its old child',()=>{const f=setup('<Border Name="Host"><TextBlock Name="Old" Text="old"/></Border>'),host=f.root.Host,old=f.root.Old;reload(f,'<Border Name="Host"><Button Name="New" Content="new" Click="Go"/></Border>');assert.equal(f.root.Host,host);assert.equal(host.Content,f.root.New);assert.equal(old._disposed,true);assert.equal(f.root.FindControl('Old'),null);f.root.New.raise('Click');assert.equal(f.root.count,1);f.root.Dispose();});
test('empty content host can be filled and cleared with no restart',()=>{const f=setup('<Border Name="Host"/>'),host=f.root.Host;reload(f,'<Border Name="Host"><TextBox Name="Input"/></Border>');const input=f.root.Input;reload(f,'<Border Name="Host"/>');assert.equal(f.root.Host,host);assert.equal(host.Content,null);assert.equal(input._disposed,true);f.root.Dispose();});
test('application content root can be replaced without replacing its owner',()=>{const f=setup('<TextBlock Name="Old"/>'),root=f.root;reload(f,'<Grid Name="New"><Button Name="B" Click="Go"/></Grid>');assert.equal(f.JB.root,root);assert.equal(root.Content,root.New);root.B.raise('Click');assert.equal(root.count,1);root.Dispose();});
test('named control moves between panel and content host with bindings and handlers intact',()=>{const input='<TextBox Name="Input" Text="{Binding Title}"/>',f=setup(row(input,'')),original=f.root.Input,a=new f.JB.ObservableObject(),b=new f.JB.ObservableObject();a.Title='a';b.Title='b';f.root.A.DataContext=a;f.root.B.DataContext=b;assert.equal(original.Text,'a');reload(f,row('',input));assert.equal(f.root.Input,original);assert.equal(original.parent,f.root.B);assert.equal(f.root.B.Content,original);assert.equal(original.Text,'b');assert.equal(a.PropertyChanged.Count,0);original.Text='updated';assert.equal(b.Title,'updated');assert.equal(a.Title,'a');reload(f,row(input,''));assert.equal(original.parent,f.root.A);assert.equal(f.root.B.Content,null);assert.equal(original.Text,'a');f.root.Dispose();});
test('reparent failure restores old ownership values scope and subscriptions',()=>{const input='<TextBox Name="Input" Text="{Binding Title}"/>',f=setup(row(input,'')),original=f.root.Input,a=new f.JB.ObservableObject(),b=new f.JB.ObservableObject();a.Title='a';b.Title='b';f.root.A.DataContext=a;f.root.B.DataContext=b;let calls=0;const flush=f.JB.flushLayout;f.JB.flushLayout=()=>{if(!calls++)throw new Error('render failed');flush();};assert.throws(()=>reload(f,row('',input)),/render failed/);assert.equal(original.parent,f.root.A);assert.equal(f.root.A.Children[0],original);assert.equal(f.root.B.Content,null);assert.equal(original.Text,'a');assert.equal(b.PropertyChanged.Count,0);assert.equal(f.JB.dev.revision,0);f.root.Dispose();});
test('explicit Children and Child property elements participate in ownership edits',()=>{const f=setup('<Border Name="Host"><Border.Child><StackPanel Name="P"><StackPanel.Children><TextBox Name="Input"/></StackPanel.Children></StackPanel></Border.Child></Border>'),input=f.root.Input;input.Text='typed';reload(f,'<Border Name="Host"><Border.Child><StackPanel Name="P"><StackPanel.Children><Button Name="Added"/><TextBox Name="Input"/></StackPanel.Children></StackPanel></Border.Child></Border>');assert.equal(f.root.P.Children[1],input);assert.equal(input.Text,'typed');f.root.Dispose();});
test('application-owned content replacement is rejected without disposing borrowed objects',()=>{const f=setup('<Border Name="Host"><TextBlock Name="Old"/></Border>'),borrowed=new f.JB.TextBox();f.root.Host.Content=borrowed;assert.throws(()=>reload(f,'<Border Name="Host"><Button Name="New"/></Border>'),/Runtime child order\/content|Structural target is absent/);assert.equal(f.root.Host.Content,borrowed);assert.equal(borrowed._disposed,false);f.root.Dispose();});
test('moving an existing subtree retains all descendant identities',()=>{const subtree='<StackPanel Name="Inner"><TextBox Name="Input" Text="initial"/><Button Name="Action" Click="Go"/></StackPanel>',f=setup(row(subtree,'')),input=f.root.Input,action=f.root.Action;input.Text='typed';reload(f,row('',subtree));assert.equal(f.root.Input,input);assert.equal(f.root.Action,action);assert.equal(input.Text,'typed');action.raise('Click');assert.equal(f.root.count,1);assert.equal(action.Click.Count,1);f.root.Dispose();});
test('renaming a retained control type remains an explicit incompatibility',()=>{const f=setup('<Border Name="Host"><TextBox Name="Input"/></Border>'),plan=planReload(f.result,build('<Border Name="Host"><Button Name="Input"/></Border>'));assert.equal(plan.compatible,false);assert.match(plan.reasons.join(),/type changed/);f.root.Dispose();});
