import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {compileProject} from '../packages/project-system/index.js';import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {PathGeometry,PathFigure,LineSegment,QuadraticBezierSegment,BezierSegment,GradientStop,LinearGradientBrush,pathData,pointList,relativePoint,vectorObject} from '../packages/avalonia-runtime/vector-model.js';
import {brush,dimension} from '../packages/avalonia-runtime/styling.js';
const folder=new URL('../examples/UpstreamCanvas/',import.meta.url),files=Object.fromEntries(['CanvasPage.xaml','CanvasPage.xaml.cs','UpstreamCanvas.csproj'].map(n=>[n,fs.readFileSync(new URL(n,folder),'utf8')]));
test('upstream Canvas XAML and codebehind match the pinned requested-fork blobs exactly',()=>{const manifest=JSON.parse(fs.readFileSync(new URL('./fixtures/upstream.json',import.meta.url),'utf8'));for(const entry of manifest.requestedLibrary.files){const b=fs.readFileSync(new URL('../'+entry.local,import.meta.url));assert.equal(crypto.createHash('sha1').update(`blob ${b.length}\0`).update(b).digest('hex'),entry.blob);}assert.equal(manifest.requestedLibrary.fullControlCatalogPassed,false);});
test('unchanged Canvas page compiles and constructs all 8 actual vector shapes in release and development',async()=>{
  for(const options of [{},{debug:true},{debug:true,cooperativeDebug:true}]){const result=compileProject(files,options);assert.equal(result.success,true,JSON.stringify(result.diagnostics));const JB=createRuntime();if(options.debug)JB.enableDevelopment({debug:result.debug,nativeBreaks:false});new Function('JB',result.code)(JB);const root=options.cooperativeDebug?await JB.dev.co.run(JB.createFromXamlSteps('ControlCatalog.Pages.CanvasPage')).promise:JB.createFromXaml('ControlCatalog.Pages.CanvasPage');const canvas=root.Content.Children[1];assert.equal(canvas.type,'Canvas');assert.deepEqual(canvas.Children.map(x=>x.type),['Rectangle','Rectangle','Ellipse','Path','Path','Line','Polygon','Polyline']);const mask=canvas.Children[0].OpacityMask;assert.ok(mask instanceof LinearGradientBrush);assert.equal(mask.GradientStops.length,2);assert.ok(canvas.Children[4].Data instanceof PathGeometry);assert.equal(pathData(canvas.Children[4].Data),'M 0,0 Q 50,0 50,-50 Q 100,-50 100,0 L 50,0 L 50,50 Z');root.Dispose();}
});
test('Canvas attached properties retain NaN defaults and actual C# getter setter behavior',()=>{const result=compileProject({'Test.cs':'public class Test {public static double Run(){var b=new Button(); Canvas.SetLeft(b,12); Canvas.SetTop(b,19);return Canvas.GetLeft(b)+Canvas.GetTop(b);}}'});assert.equal(result.success,true,JSON.stringify(result.diagnostics));const JB=createRuntime();new Function('JB',result.code)(JB);assert.equal(JB.types.get('Test').Run(),31);const c=new JB.Button();assert.ok(Number.isNaN(JB.Canvas.GetRight(c)));JB.Canvas.SetRight(c,20);assert.equal(c.GetValue('Canvas.Right'),20);c.ClearValue(JB.Canvas.RightProperty);assert.ok(Number.isNaN(JB.Canvas.GetRight(c)));assert.throws(()=>JB.Canvas.SetLeft(c,Infinity));c.Dispose();});
test('HSV alpha colors normalize to safe RGB while HSL uses native color syntax',()=>{assert.equal(brush('hsva(240, 83%, 73%, 90%)'),'rgba(32,32,186,0.9)');assert.equal(brush('hsv(120,100%,100%)'),'rgba(0,255,0,1)');assert.equal(brush({Color:{toString:()=> 'hsv(120,100%,100%)'}}),'rgba(0,255,0,1)');assert.equal(dimension(NaN),'');assert.equal(brush('hsl(5, 85%, 85%)'),'hsl(5, 85%, 85%)');for(const value of ['hsv(1,200%,30%)','hsva(0,0%,0%)','hsv(0,0%,0%,1)','url(https://external/)'])assert.equal(brush(value),'');});
test('vector model preserves curves explicit closure and finite bounds',()=>{const p=new PathGeometry(),f=new PathFigure();p.Figures.Add(f);f.StartPoint='2,-4';f.Segments.Add(new LineSegment('4,6'));const q=new QuadraticBezierSegment();q.Point1='3,2';q.Point2='4,1';f.Segments.Add(q);const c=new BezierSegment();c.Point3='9,3';f.Segments.Add(c);f.IsClosed=true;assert.equal(pathData(p),'M 2,-4 L 4,6 Q 3,2 4,1 C 0,0 0,0 9,3 Z');assert.equal(pointList('1,2 3,-4'),'1,2 3,-4');assert.deepEqual(relativePoint('20%,50%'),{units:'objectBoundingBox',values:[.2,.5]});assert.throws(()=>relativePoint('1%,2'));assert.throws(()=>pointList('1,2,3'));f.StartPoint='Infinity,0';assert.throws(()=>pathData(p));assert.throws(()=>pathData('M0,0<script>'));});
test('unimplemented vector properties and compound object slots are diagnosed rather than dropped',()=>{for(const xml of ['<PathGeometry Unknown="3"/>','<LinearGradientBrush Bad="3"/>','<PathGeometry><PathGeometry.Bad/></PathGeometry>']){const r=compileProject({'T.axaml':xml});assert.equal(r.success,false);}assert.throws(()=>vectorObject({type:'LineSegment',attributes:{},children:[{kind:'object'}]},()=>null,()=>null));});
