import test from 'node:test';
import assert from 'node:assert/strict';
import {compileProject} from '../packages/project-system/index.js';
import {createRuntime} from '../packages/avalonia-runtime/index.js';
import {planReload, reloadScript} from '../packages/development/reload.js';
import {duplicateControl,insertControl} from '../packages/development/designer.js';
const doc=children=>`<UserControl xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" x:Class="V"><StackPanel Name="P">${children}</StackPanel></UserControl>`;
const cs='public partial class V : UserControl { public int count=0; public void Clicked(object s, RoutedEventArgs e){count++;} }';
function fixture(children){const files={'V.axaml':doc(children),'V.cs':cs},result=compileProject(files,{debug:true});assert.equal(result.success,true,JSON.stringify(result.diagnostics));const JB=createRuntime(),events=[];JB.enableDevelopment({debug:result.debug,nativeBreaks:false,report:(event,data)=>events.push({event,data})});new Function('JB',result.code)(JB);JB.root=JB.createFromXaml('V');return {JB,events,files,result,root:JB.root};}
function reload(f,children,extra={}){const files={...f.files,'V.axaml':doc(children),...extra},next=compileProject(files,{debug:true});assert.equal(next.success,true,JSON.stringify(next.diagnostics));const plan=planReload(f.result,next);assert.equal(plan.compatible,true,JSON.stringify(plan.reasons));new Function('JB',reloadScript(plan,f.result,next,f.JB.dev.revision+1).replace('(globalThis.Jailbreak)','(JB)'))(f.JB);f.result=next;f.files=files;return plan;}
test('named insert/delete/reorder retains root and user state; names point at the new controls',()=>{const f=fixture('<TextBox Name="Input" Text="initial"/><Button Name="Button" Click="Clicked" Content="Run"/>'),{root,JB}=f,input=root.Input,button=root.Button;input.Text='typed';button.raise('Click');reload(f,'<Button Name="Button" Click="Clicked" Content="Run"/><TextBlock Name="Added" Text="New"/><TextBox Name="Input" Text="initial"/>');assert.equal(root,JB.root);assert.equal(root.Input,input);assert.equal(root.Button,button);assert.equal(input.Text,'typed');assert.equal(root.count,1);assert.deepEqual([...root.P.Children],[button,root.Added,input]);const added=root.Added;reload(f,'<Button Name="Button" Click="Clicked" Content="Run"/><TextBox Name="Input" Text="initial"/>');assert.equal(added._disposed,true);assert.equal(root.Added,undefined);assert.equal(root.FindControl('Added'),null);assert.equal(root.FindControl('Input'),input);root.Dispose();});
test('new event handlers use the current compiled code and are not installed twice',()=>{const f=fixture('<TextBox Name="Input"/>');reload(f,'<Button Name="Added" Content="Run" Click="Clicked"/><TextBox Name="Input"/>');f.root.Added.raise('Click');assert.equal(f.root.count,1);const added=f.root.Added;reload(f,'<TextBox Name="Input"/><Button Name="Added" Content="Run now" Click="Clicked"/>',{'V.cs':cs.replace('count++','count+=10')});added.raise('Click');assert.equal(f.root.count,11);assert.equal(added.Click.Count,1);f.root.Dispose();});
test('nested inserted panels export names and participate in subsequent property reloads',()=>{const f=fixture('<TextBox Name="Input"/>');reload(f,'<TextBox Name="Input"/><Grid Name="Inner"><TextBlock Name="Message" Text="One"/></Grid>');assert.equal(f.root.FindControl('Message'),f.root.Message);const message=f.root.Message;reload(f,'<TextBox Name="Input"/><Grid Name="Inner"><TextBlock Name="Message" Text="Two"/><Button Name="Other"/></Grid>');assert.equal(f.root.Message,message);assert.equal(message.Text,'Two');assert.equal(f.JB.dev.inspect(message.uid).source.offset,f.files['V.axaml'].indexOf('<TextBlock'));f.root.Dispose();});
test('C# appended controls retain identity when a XAML panel is reconciled',()=>{const f=fixture('<TextBox Name="Input"/>'),code=new f.JB.Button();code.Content='from C#';f.root.P.Children.Add(code);reload(f,'<TextBox Name="Input"/><CheckBox Content="Added"/>');assert.equal(f.root.P.Children.at(-1),code);assert.equal(code._disposed,false);assert.equal(f.root.Input.parent,f.root.P);f.root.Dispose();});
test('runtime reordering and interleaved external children fail preflight unchanged',()=>{const f=fixture('<TextBox Name="Input"/><Button Name="Button"/>'),code=new f.JB.Button();f.root.P.Children.splice(1,0,code);const before=[...f.root.P.Children];assert.throws(()=>reload(f,'<TextBox Name="Input"/><Button Name="Button"/><CheckBox/>'),/Runtime child order/);assert.deepEqual([...f.root.P.Children],before);assert.equal(f.JB.dev.revision,0);f.root.Dispose();});
test('failed structural render restores hierarchy property stores names and methods',()=>{const f=fixture('<TextBox Name="Input" Text="initial"/><Button Name="Old" Click="Clicked"/>'),{root,JB}=f,old=root.Old,input=root.Input;input.Text='typed';const flush=JB.flushLayout;let called=0;JB.flushLayout=()=>{if(!called++)throw new Error('render failed');return flush();};assert.throws(()=>reload(f,'<TextBox Name="Input" Text="initial"/><Button Name="New" Click="Clicked"/>'),/render failed/);assert.deepEqual([...root.P.Children],[input,old]);assert.equal(root.FindControl('Old'),old);assert.equal(root.New,undefined);assert.equal(root.FindControl('New'),null);assert.equal(input.Text,'typed');assert.equal(old._disposed,false);assert.equal(JB.dev.revision,0);assert.equal(JB.dev.tree().some(n=>n.name==='New'),false);root.Dispose();});
test('missing event handler in a staged subtree cannot alter the live app',()=>{const f=fixture('<TextBox Name="Input"/>');assert.throws(()=>reload(f,'<TextBox Name="Input"/><Button Name="New" Click="DoesNotExist"/>'),/handler/);assert.equal(f.root.P.Children.length,1);assert.equal(f.root.New,undefined);assert.equal(f.JB.dev.revision,0);f.root.Dispose();});
test('ambiguous anonymous deletion and unsupported new bindings require restart',()=>{const f=fixture('<TextBox Text="same"/><TextBox Text="same"/>');for(const children of ['<TextBox Text="same"/>','<TextBox Text="same"/><TextBox Text="same"/><TextBlock Text="{Binding Title}"/>']){const n=compileProject({...f.files,'V.axaml':doc(children)},{debug:true});assert.equal(planReload(f.result,n).compatible,false);}f.root.Dispose();});
test('template and non-panel structural changes are not claimed as compatible',()=>{const f=fixture('<Border Name="Border"><TextBlock Text="A"/></Border>');const next=compileProject({...f.files,'V.axaml':doc('<Border Name="Border"/>')},{debug:true});assert.equal(planReload(f.result,next).compatible,false);f.root.Dispose();});
test('removed binding subscriptions are released only after successful commit',()=>{const f=fixture('<TextBlock Name="Label" Text="{Binding Title}"/><TextBox Name="Input"/>'),model=new f.JB.ObservableObject();model.Title='Title';f.root.DataContext=model;const label=f.root.Label,previous=model.PropertyChanged.Count;assert.ok(previous>0);reload(f,'<TextBox Name="Input"/>');assert.equal(label._disposed,true);assert.ok(model.PropertyChanged.Count<previous);f.root.Dispose();});
test('surviving ElementName references block removal instead of holding a disposed target',()=>{const f=fixture('<TextBox Name="Input"/><TextBlock Text="{Binding Text, ElementName=Input}"/>');const next=compileProject({...f.files,'V.axaml':doc('<TextBlock Text="{Binding Text, ElementName=Input}"/>')},{debug:true});assert.equal(planReload(f.result,next).compatible,false);f.root.Dispose();});
test('repeated add/remove cycles preserve method handlers and never revive disposed instances',()=>{const f=fixture('<TextBox Name="Input" Text="initial"/>'),input=f.root.Input;input.Text='typed';for(let i=0;i<12;i++){reload(f,'<TextBox Name="Input" Text="initial"/><Button Name="Action" Click="Clicked"/>');const action=f.root.Action;action.raise('Click');reload(f,'<TextBox Name="Input" Text="initial"/>');assert.equal(action._disposed,true);assert.equal(action.Click.Count,0);assert.equal(f.root.Input,input);}assert.equal(f.root.count,12);assert.equal(input.Text,'typed');assert.equal(f.JB.dev.revision,24);f.root.Dispose();});
test('names cannot overwrite a live C# field even when the field is not a control',()=>{const f=fixture('<TextBox Name="Input"/>');assert.throws(()=>reload(f,'<TextBox Name="Input"/><Button Name="count"/>'),/collides/);assert.equal(f.root.count,0);assert.equal(f.root.FindControl('count'),null);f.root.Dispose();});

test('designer duplicate generates distinct names and preserves comments and CRLF',()=>{const text='<StackPanel>\r\n  <Border Name="Box"><!--keep--><TextBlock Name="Label" Text="Text"/></Border>\r\n</StackPanel>',t=duplicateControl(text,'V.axaml',text.indexOf('<Border'));assert.match(t.after,/Name="BoxCopy"/);assert.match(t.after,/Name="LabelCopy"/);assert.equal(t.after.split('<!--keep-->').length,3);assert.ok(t.after.includes('\r\n'));assert.match(insertControl('<StackPanel><Button Name="Button1"/></StackPanel>','V.axaml',0,'Button').after,/Name="Button2"/);});
test('designer duplication blocks ambiguous reference remapping',()=>{assert.throws(()=>duplicateControl('<StackPanel><TextBlock Text="{Binding Name}"/></StackPanel>','V.axaml',12),/bindings/);});

test('observer failures cannot prevent removed controls from releasing subscriptions',()=>{const f=fixture('<TextBlock Name="Label" Text="{Binding Title}"/><TextBox Name="Input"/>'),model=new f.JB.ObservableObject();model.Title='Title';f.root.DataContext=model;const label=f.root.Label;label.Unloaded.add(()=>{throw new Error('unload failed');});let released=false;label.track(()=>{throw new Error('first disposer failed');});label.track(()=>{released=true;});reload(f,'<TextBox Name="Input"/>');assert.equal(label._disposed,true);assert.equal(released,true);assert.equal(label.PropertyChanged.Count,0);assert.ok(f.events.some(e=>e.event==='reload-warning'));f.root.Dispose();});
