const templates={
  xaml:{label:'XAML view',extension:'.axaml',source:'<UserControl xmlns="https://github.com/avaloniaui">\n  <StackPanel Margin="24" Spacing="12">\n    <TextBlock Text="New view" FontSize="24" />\n    <Button Content="Hello, browser" />\n  </StackPanel>\n</UserControl>\n'},
  csharp:{label:'C# class',extension:'.cs',source:'namespace MyApp;\n\npublic class CLASS_NAME\n{\n}\n'},
  project:{label:'Project file',extension:'.csproj',source:'<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n  </PropertyGroup>\n</Project>\n'}
};
export function newItemSource(path,kind){if(!/^[\w .\-/]+\.(cs|a?xaml|csproj|props|targets|slnx)$/.test(path)||path.includes('..')||path.startsWith('/')||path.split('/').some(p=>!p.trim()))throw new Error('Use a relative C#, XAML or project file path.');const t=templates[kind];if(!t||!path.endsWith(t.extension))throw new Error('The file extension must match the selected item type.');const name=path.split('/').at(-1).replace(/\.[^.]+$/,'');if(kind==='csharp'&&!/^[A-Za-z_]\w*$/.test(name))throw new Error('A C# class name must be a valid identifier.');return t.source.replace('CLASS_NAME',name);}
export function createNewItemDialog({document:doc=globalThis.document,create}){
  const el=(tag,text='')=>{const n=doc.createElement(tag);n.textContent=text;return n;},dialog=el('dialog');dialog.id='studio-new-item';dialog.setAttribute('aria-labelledby','studio-new-title');const form=el('form');form.method='dialog';const title=el('h2','Add new item');title.id='studio-new-title';const note=el('p','Create a source file in the current workspace. Files stay in this browser.');
  const choices=el('div');choices.className='studio-item-choices';let kind='xaml';const name=el('input');name.id='studio-new-path';name.value='Views/NewView.axaml';name.required=true;name.setAttribute('aria-label','New item path');const label=el('label','Name and relative path');label.htmlFor=name.id;
  for(const [key,t]of Object.entries(templates)){const b=el('button',t.label);b.type='button';b.dataset.kind=key;b.setAttribute('aria-pressed',String(key===kind));b.onclick=()=>{kind=key;name.value={xaml:'Views/NewView.axaml',csharp:'Models/NewClass.cs',project:'NewProject.csproj'}[key];choices.querySelectorAll('button').forEach(c=>c.setAttribute('aria-pressed',String(c===b)));name.focus();};choices.append(b);}
  const error=el('div');error.id='studio-new-error';error.setAttribute('role','alert');const actions=el('div');actions.className='studio-dialog-actions';const cancel=el('button','Cancel');cancel.type='button';cancel.onclick=()=>dialog.close();const submit=el('button','Add');submit.type='submit';submit.className='primary';actions.append(cancel,submit);form.append(title,note,choices,label,name,error,actions);dialog.append(form);doc.body.append(dialog);
  form.onsubmit=e=>{e.preventDefault();try{create(name.value.trim(),newItemSource(name.value.trim(),kind));dialog.close();}catch(e){error.textContent=e.message;}};
  return {open(){error.textContent='';dialog.showModal();name.focus();name.select();},dispose(){dialog.remove();}};
}
