import {Workspace,createApplicationHtml,runtimeModulePaths} from '../packages/project/index.js';
const $=id=>document.getElementById(id),state={workspace:new Workspace(),active:null,compilation:null,worker:null,request:0,channel:'',timer:null,entry:null,tab:'source'};
const editor=$('editor'),storageKey='jailbreak.browser.workspace.v1';let runtimeSources;
const runtimeReady=Promise.all(runtimeModulePaths.map(async p=>{const response=await fetch(`../packages/${p}`);if(!response.ok)throw new Error('Cannot load runtime '+p);return response.text();})).then(s=>runtimeSources=s);
function log(message,severity='info',d={}){const row=document.createElement('div');row.className='diagnostic '+severity;const mark=document.createElement('span');mark.textContent=severity==='success'?'✓':severity==='error'?'×':severity==='warning'?'!':'·';const text=document.createElement('button');text.textContent=(d.file?`${d.file}(${d.line||1},${d.column||1}) `:'')+(d.code?d.code+': ':'')+message;text.onclick=()=>{if(d.file&&state.workspace.get(d.file)!=null){openFile(d.file);const offset=editor.value.split('\n').slice(0,(d.line||1)-1).join('\n').length+(d.line>1?1:0)+(d.column||1)-1;editor.focus();editor.setSelectionRange(offset,offset);}};row.append(mark,text);$('diagnostics').append(row);$('diagnostics').scrollTop=$('diagnostics').scrollHeight;}
function status(text,error=false){$('status').textContent=text;$('status-dot').classList.toggle('error',error);}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({files:state.workspace.toJSON(),active:state.active}));$('file-state').textContent='Saved locally';}catch{$('file-state').textContent='Storage full — download workspace';}}
function updateLines(){const count=editor.value.split('\n').length;$('lines').textContent=Array.from({length:count},(_,i)=>i+1).join('\n');updateCursor();}
function updateCursor(){const head=editor.value.slice(0,editor.selectionStart);$('cursor').textContent=`Ln ${head.split('\n').length}, Col ${head.length-head.lastIndexOf('\n')}`;}
function showTab(tab){state.tab=tab;for(const e of document.querySelectorAll('[data-tab]'))e.classList.toggle('selected',e.dataset.tab===tab);$('editor-wrap').hidden=tab!=='source';$('output').hidden=tab!=='output';$('graph').hidden=tab!=='graph';}
function renderFiles(){const filter=$('filter').value.toLowerCase();$('files').replaceChildren();for(const path of state.workspace.paths().filter(p=>p.toLowerCase().includes(filter))){const b=document.createElement('button');b.className='file'+(path===state.active?' active':'');b.title=path;const icon=document.createElement('span');icon.className='file-icon';icon.textContent=path.endsWith('.cs')?'C#':/\.(xaml|axaml)$/.test(path)?'<>':path.endsWith('.csproj')?'◇':'≡';const label=document.createElement('span');label.className='file-name';label.textContent=path.split('/').at(-1);b.append(icon,label);b.onclick=()=>openFile(path);$('files').append(b);}$('file-count').textContent=state.workspace.paths().length;}
function openFile(path){state.active=path;editor.value=state.workspace.get(path)||'';$('filename').textContent=path;$('language').textContent=path.split('.').at(-1).toUpperCase();updateLines();renderFiles();showTab('source');}
function replaceWorkspace(files,name,active){state.worker?.terminate();clearTimeout(state.timer);state.workspace=new Workspace(files);state.entry=null;state.compilation=null;$('workspace-name').textContent=name;const path=active||state.workspace.paths().find(p=>p.endsWith('.axaml')||p.endsWith('.xaml'))||state.workspace.paths()[0];if(path)openFile(path);persist();}
function stop(){state.worker?.terminate();clearTimeout(state.timer);state.request++;document.body.classList.remove('busy');$('run').disabled=false;$('preview').srcdoc='';$('empty-preview').hidden=false;status('Stopped');}
async function build(run=true){if(!state.workspace.paths().length)return;state.worker?.terminate();clearTimeout(state.timer);const id=++state.request;$('diagnostics').replaceChildren();status('Compiling…');document.body.classList.add('busy');$('run').disabled=true;
 const worker=state.worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});state.timer=setTimeout(()=>{worker.terminate();$('run').disabled=false;document.body.classList.remove('busy');log('Build exceeded the worker time limit. Simplify the source or inspect compiler recursion.','error');status('Build timed out',true);},15000);
 worker.onerror=e=>{clearTimeout(state.timer);$('run').disabled=false;document.body.classList.remove('busy');log(e.message,'error');status('Worker failed',true);};
 worker.onmessage=async({data})=>{if(data.id!==state.request)return;clearTimeout(state.timer);worker.terminate();state.compilation=data.result;const c=data.result;document.body.classList.remove('busy');$('run').disabled=false;$('build-time').textContent=`${data.elapsed.toFixed(1)} ms`;$('problem-count').textContent=c.diagnostics.length;for(const d of c.diagnostics)log(d.message,d.severity,d);$('output').textContent=c.code||'Build failed. Resolve diagnostics before execution.';$('graph').textContent=JSON.stringify({entry:c.entry,projects:c.projects,classes:c.classes,files:c.files},null,2);
 $('entry').replaceChildren();for(const v of c.views||[]){if(v.ir?.type==='Application')continue;const o=document.createElement('option');o.value=v.runtimeName;o.textContent=v.className?.split('.').at(-1)||v.path;o.selected=v.runtimeName===c.entry;$('entry').append(o);}
 if(!c.ok){status('Build failed',true);log('Preview was not executed because the build contains errors.','error');return;}log(`Build succeeded · ${c.files.length} source files · ${c.classes.length} C# classes · ${c.views.length} XAML views`,'success');status('Build succeeded');$('metrics').textContent=`${c.files.length} files · ${c.views.length} views · ${c.code.length.toLocaleString()} JS bytes`;
 if(run){try{await runtimeReady;if(id!==state.request)return;state.channel='jailbreak-'+(crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2));$('preview').srcdoc=createApplicationHtml(c,runtimeSources,{channel:state.channel});$('empty-preview').hidden=true;}catch(e){log(e.message,'error');status('Preview failed',true);}}};
 const project=state.workspace.paths().find(p=>p.endsWith('.sln'))||null;worker.postMessage({id,files:state.workspace.toJSON(),options:{project,entry:state.entry}});
}
async function loadSample(name){const definitions={demo:['../samples/',['Demo.sln','Demo.csproj','MainView.axaml','MainView.axaml.cs'],'Control laboratory'],checkbox:['../fixtures/control-catalog/',['CheckBoxPage.xaml','CheckBoxPage.xaml.cs'],'Upstream · CheckBox'],radio:['../fixtures/control-catalog/',['RadioButtonPage.xaml','RadioButtonPage.xaml.cs'],'Upstream · RadioButton']};const[base,files,title]=definitions[name];const entries=await Promise.all(files.map(async path=>{const r=await fetch(base+path);if(!r.ok)throw new Error('Failed to load '+path);return[path,await r.text()];}));replaceWorkspace(Object.fromEntries(entries),title);build();}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importFiles(list){try{const files=[...list];if(files.length===1&&files[0].name.endsWith('.json')){const data=JSON.parse(await files[0].text());replaceWorkspace(data.files||data,'Imported workspace',data.active);log('Workspace loaded. Build & run when ready.');return;}const accepted=files.filter(f=>/\.(cs|csproj|sln|xaml|axaml)$/i.test(f.name)&&!/(^|\/)(bin|obj|node_modules|\.git)\//.test(f.webkitRelativePath));if(accepted.length>1500||accepted.reduce((n,f)=>n+f.size,0)>25*1024*1024)throw new Error('Workspace limit: 1,500 files / 25 MB');const folder=accepted[0]?.webkitRelativePath.split('/')[0];const entries=await Promise.all(accepted.map(async f=>[(f.webkitRelativePath?f.webkitRelativePath.split('/').slice(1).join('/'):f.name),await f.text()]));if(!entries.length)throw new Error('No supported source files selected');if(new Set(entries.map(e=>e[0])).size!==entries.length)throw new Error('Duplicate filenames; use Open folder to preserve project paths');replaceWorkspace(Object.fromEntries(entries),folder||'Imported source');log('Source loaded locally. Select Build & run to execute trusted source.');status('Workspace loaded');}catch(e){log(e.message,'error');}}
editor.addEventListener('input',()=>{if(!state.active)return;state.workspace.set(state.active,editor.value);updateLines();$('file-state').textContent='Modified';clearTimeout(window.saveTimer);window.saveTimer=setTimeout(persist,300);});editor.addEventListener('scroll',()=>$('lines').scrollTop=editor.scrollTop);editor.addEventListener('click',updateCursor);editor.addEventListener('keyup',updateCursor);editor.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();editor.setRangeText('    ',editor.selectionStart,editor.selectionEnd,'end');editor.dispatchEvent(new Event('input'));}});
$('run').onclick=()=>build();$('stop').onclick=stop;$('entry').onchange=()=>{state.entry=$('entry').value;build();};$('sample').onchange=()=>loadSample($('sample').value).catch(e=>log(e.message,'error'));$('filter').oninput=renderFiles;for(const t of document.querySelectorAll('[data-tab]'))t.onclick=()=>showTab(t.dataset.tab);
$('open-folder').onclick=()=>$('folder-input').click();$('open-files').onclick=()=>$('file-input').click();for(const id of ['folder-input','file-input'])$(id).onchange=e=>importFiles(e.target.files);
$('save').onclick=()=>download('jailbreak-workspace.json',JSON.stringify({format:'jailbreak-workspace-v1',files:state.workspace.toJSON(),active:state.active},null,2));
$('export').onclick=async()=>{if(!state.compilation?.ok){log('Build successfully before exporting an application.','warning');return;}await runtimeReady;download('jailbreak-app.html',createApplicationHtml(state.compilation,runtimeSources),'text/html');};
$('new-file').onclick=()=>{const path=prompt('New source file path','NewView.axaml');if(!path)return;try{if(state.workspace.get(path)!=null)throw new Error('File already exists');state.workspace.set(path,path.endsWith('.cs')?'namespace Demo;\npublic class Model { }\n':'<UserControl xmlns="https://github.com/avaloniaui">\n  <TextBlock Text="Hello" />\n</UserControl>\n');openFile(path);persist();}catch(e){log(e.message,'error');}};
$('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('jailbreak.theme',document.documentElement.dataset.theme);}catch{}};
$('mobile').onclick=()=>$('preview-stage').classList.toggle('compact');$('show-help').onclick=()=>$('help').showModal();$('close-help').onclick=()=>$('help').close();$('clear-log').onclick=()=>$('diagnostics').replaceChildren();
window.addEventListener('message',event=>{const m=event.data;if(event.source!==$('preview').contentWindow||m?.channel!==state.channel)return;if(m.kind==='ready'){status('Application running');log(`Running ${m.value.entry} · ${m.value.controls} controls · ${m.value.bindings} bindings`,'success');}else if(m.kind==='diagnostic')log(m.value.message,m.value.severity||'warning',m.value);else if(m.kind==='error'){status('Runtime error',true);log(m.value,'error');}else if(m.kind==='log')log(String(m.value));});
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();build();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('save').click();}});
try{document.documentElement.dataset.theme=localStorage.getItem('jailbreak.theme')||'light';const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.files){replaceWorkspace(saved.files,'Restored workspace',saved.active);log('Workspace restored. Build & run to execute.');}else loadSample('demo').catch(e=>log(e.message,'error'));}catch{loadSample('demo').catch(e=>log(e.message,'error'));}
window.jailbreakIDE={state,build,loadSample};
