<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>$(DefineConstants);APP</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Native.cs" />
    <Compile Remove="DebugOnly.cs" Condition="'$(Configuration)' == 'Release'" />
    <ProjectReference Include="../Library/Library.csproj" />
  </ItemGroup>
</Project>
